"""Character portrait loader + placer.

Portraits are pre-generated by `scripts/generate_portraits.py` and stored in
`data/portraits/{agent_id}.png`. This module loads them on demand.
"""

from __future__ import annotations

from functools import lru_cache

from PIL import Image

from ..assets import portrait_path


@lru_cache(maxsize=16)
def load_portrait(agent_id: str) -> Image.Image:
    """Return the pre-generated portrait for `agent_id` as an RGBA image."""
    path = portrait_path(agent_id)
    if not path.exists():
        raise FileNotFoundError(
            f"portrait not found: {path} — run `scripts/generate_portraits.py`"
        )
    return Image.open(path).convert("RGBA")


def scaled_portrait(agent_id: str, target_width: int) -> Image.Image:
    """Return the portrait resized to `target_width` px wide.

    Uses NEAREST resampling to preserve the pixel-art aesthetic — BILINEAR
    blurs the 32x48 sprite grid and kills the look.
    """
    p = load_portrait(agent_id)
    ratio = target_width / p.width
    new_h = max(1, round(p.height * ratio))
    return p.resize((target_width, new_h), resample=Image.Resampling.NEAREST)
